# Generated by Django 6.0.7 on 2026-07-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('college_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('college_type', models.CharField(choices=[('GOVT', 'Government'), ('AIDED', 'Government Aided'), ('SELF', 'Self Financing')], max_length=10)),
            ],
        ),
    ]
