# Generated by Django 6.0.7 on 2026-07-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('OC', 'Open Competition'), ('BC', 'Backward Class'), ('BCM', 'Backward Class Muslim'), ('MBC', 'Most Backward Class'), ('SC', 'Scheduled Caste'), ('SCA', 'Scheduled Caste Arunthathiyar'), ('ST', 'Scheduled Tribe')], max_length=3)),
                ('opening_cutoff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('closing_cutoff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
            ],
        ),
    ]
