# Generated by Django 6.0.7 on 2026-07-10 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutoff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mathematics', models.PositiveIntegerField()),
                ('physics', models.PositiveIntegerField()),
                ('chemistry', models.PositiveIntegerField()),
                ('cutoff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('OC', 'Open Competition'), ('BC', 'Backward Class'), ('BCM', 'Backward Class Muslim'), ('MBC', 'Most Backward Class'), ('SC', 'Scheduled Caste'), ('SCA', 'Scheduled Caste Arunthathiyar'), ('ST', 'Scheduled Tribe')], max_length=3)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
