# Generated by Django 6.0.7 on 2026-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_branch_unique_branch_per_college'),
        ('cutoff', '0002_calculationhistory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cutoff',
            constraint=models.UniqueConstraint(fields=('college', 'branch', 'year', 'category'), name='unique_cutoff_record'),
        ),
    ]
